Title: Chipprogrammer
Slogan: Electronics for Everyone
baseurl: "/"
url: "https://chipprogrammers.github.io"
Author: Arun K Soman
Author_img: "/static/IMG/Arun.jpg"

enableTags: true
tagarray: []

logo: "/static/IMG/logo.svg"
paginate: 4
paginate_path: "/blog/page:num/"
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
